# Importing Libraries and csv Files

In [1]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lejua\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lejua\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lejua\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
from nltk.corpus import stopwords
from sklearn import feature_extraction, linear_model, model_selection, preprocessing

In [4]:
import re
# https://www.scaler.com/topics/remove-special-characters-from-string-python/
# re : Regular expressions form a pattern we can use to search for special characters in a string. 
# This property is used in functions to remove special characters from strings in python

In [5]:
#train = pd.read_csv('/Users/elinakelly/Desktop/JuanJo Kaggle/Kaggle Data 1/train.csv')
#test = pd.read_csv('/Users/elinakelly/Desktop/JuanJo Kaggle/Kaggle Data 1/test.csv')

In [6]:
train = pd.read_csv('Data/train.csv')
test = pd.read_csv('Data/test.csv')

In [7]:
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [8]:
train.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [9]:
train.dtypes

id           int64
keyword     object
location    object
text        object
target       int64
dtype: object

In [10]:
# COUNT NUMBER OF REAL DISASTER TWEETS
train["target"].value_counts()

0    4342
1    3271
Name: target, dtype: int64

# I/ Pre-Processing

-> Remove site links

In [11]:
train['text'] = train['text'].str.replace('http[^\s]*',"")
test['text'] = test['text'].str.replace('http[^\s]*',"")

C:\Users\lejua\AppData\Local\Temp/ipykernel_23116/2720572779.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  train['text'] = train['text'].str.replace('http[^\s]*',"")
C:\Users\lejua\AppData\Local\Temp/ipykernel_23116/2720572779.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  test['text'] = test['text'].str.replace('http[^\s]*',"")


-> Remove special characters

In [12]:
train['txt'] = train['text'].apply(lambda x : re.sub("[^A-Z]", " ", str(x),0,re.IGNORECASE))
test['txt'] = test['text'].apply(lambda x : re.sub("[^A-Z]", " ", str(x),0,re.IGNORECASE))

-> Convert to string

In [13]:
train['txt'] = train['txt'].astype('string')
test['txt'] = test['txt'].astype('string')

In [14]:
train['txt']

0       Our Deeds are the Reason of this  earthquake M...
1                  Forest fire near La Ronge Sask  Canada
2       All residents asked to  shelter in place  are ...
3              people receive  wildfires evacuation or...
4       Just got sent this photo from Ruby  Alaska as ...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609     aria ahrary  TheTawniest The out of control w...
7610          M            UTC   km S of Volcano Hawaii  
7611    Police investigating after an e bike collided ...
7612    The Latest  More Homes Razed by Northern Calif...
Name: txt, Length: 7613, dtype: string

-> Remove stopwords

In [15]:
stop_words = stopwords.words('english')
train['txt'] = train['txt'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
test['txt'] = test['txt'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

-> Convert to Lower Case

In [16]:
train['txt'] = train['txt'].apply(lambda x: x.lower())
test['txt'] = test['txt'].apply(lambda x: x.lower())

-> Remove Strings with 1 letter

In [17]:
train['txt'] =  train['txt'].apply(lambda x: ' '.join( [w for w in x.split() if len(w)>1] ))
test['txt'] =  test['txt'].apply(lambda x: ' '.join( [w for w in x.split() if len(w)>1] ))

In [18]:
train['txt']

0        our deeds reason earthquake may allah forgive us
1                   forest fire near la ronge sask canada
2       all residents asked shelter place notified off...
3       people receive wildfires evacuation orders cal...
4       just got sent photo ruby alaska smoke wildfire...
                              ...                        
7608    two giant cranes holding bridge collapse nearb...
7609    aria ahrary thetawniest the control wild fires...
7610                                utc km volcano hawaii
7611    police investigating bike collided car little ...
7612    the latest more homes razed northern californi...
Name: txt, Length: 7613, dtype: object

-> Tokenisation & Lemmatisation

In [19]:
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()

def lemmatize_text(text):
    return [lemmatizer.lemmatize(w) for w in w_tokenizer.tokenize(text)]

train['txt'] = train['txt'].apply(lemmatize_text)
test['txt'] = test['txt'].apply(lemmatize_text)

In [20]:
train['txt'] = train['txt'].apply(lambda x: ' '.join( [w for w in x]))
test['txt'] = test['txt'].apply(lambda x: ' '.join( [w for w in x]))

In [21]:
train['txt']

0          our deed reason earthquake may allah forgive u
1                   forest fire near la ronge sask canada
2       all resident asked shelter place notified offi...
3       people receive wildfire evacuation order calif...
4       just got sent photo ruby alaska smoke wildfire...
                              ...                        
7608    two giant crane holding bridge collapse nearby...
7609    aria ahrary thetawniest the control wild fire ...
7610                                utc km volcano hawaii
7611    police investigating bike collided car little ...
7612    the latest more home razed northern california...
Name: txt, Length: 7613, dtype: object

# II/ Applying Algorithms

In [22]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [23]:
vocab_size = 10000
embedding_dim = 16
max_length = 100
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
training_size = 20000

In [24]:
tokenizer = Tokenizer(num_words = vocab_size, oov_token= oov_tok) #the OOV allows for new words to be tokenized that were not pressent on the training data
tokenizer.fit_on_texts(train["txt"])
word_index = tokenizer.word_index
print(word_index)


{'<OOV>': 1, 'the': 2, 'fire': 3, 'like': 4, 'amp': 5, 'get': 6, 'new': 7, 'via': 8, 'news': 9, 'one': 10, 'in': 11, 'people': 12, 'it': 13, 'time': 14, 'year': 15, 'video': 16, 'disaster': 17, 'emergency': 18, 'body': 19, 'day': 20, 'you': 21, 'home': 22, 'police': 23, 'building': 24, 'would': 25, 'life': 26, 'family': 27, 'go': 28, 'say': 29, 'this': 30, 'to': 31, 'still': 32, 'u': 33, 'storm': 34, 'my': 35, 'crash': 36, 'is': 37, 'we': 38, 'back': 39, 'california': 40, 'burning': 41, 'bomb': 42, 'look': 43, 'know': 44, 'suicide': 45, 'man': 46, 'death': 47, 'world': 48, 'train': 49, 'flood': 50, 'car': 51, 'got': 52, 'see': 53, 'rt': 54, 'attack': 55, 'first': 56, 'love': 57, 'and': 58, 'two': 59, 'make': 60, 'going': 61, 'nuclear': 62, 'pm': 63, 'today': 64, 'let': 65, 'war': 66, 'dead': 67, 'killed': 68, 'accident': 69, 'youtube': 70, 'if': 71, 'want': 72, 'hiroshima': 73, 'gt': 74, 'full': 75, 'woman': 76, 'need': 77, 'of': 78, 'old': 79, 'take': 80, 'weapon': 81, 'may': 82, 'wha

In [25]:
train['token'] = tokenizer.texts_to_sequences(train['txt'])
test['token'] = tokenizer.texts_to_sequences(test['txt'])
print (test['token'])

0                                [175, 832, 1806, 51, 36]
1                   [430, 196, 1109, 123, 475, 1714, 169]
2       [130, 3, 684, 3208, 1, 4531, 791, 492, 1297, 301]
3                                   [413, 3512, 6391, 96]
4                              [165, 634, 128, 294, 1115]
                              ...                        
3258                  [196, 1028, 2675, 2676, 1028, 1, 1]
3259    [34, 4534, 1062, 92, 251, 35, 123, 5, 763, 737...
3260                                 [890, 568, 327, 793]
3261                    [5503, 331, 388, 207, 1601, 1776]
3262                    [5231, 2583, 1470, 18, 104, 3939]
Name: token, Length: 3263, dtype: object


In [26]:
training_sentences = pad_sequences(train['token'],  maxlen=max_length, padding=padding_type, truncating=trunc_type)
test_sentences = pad_sequences(test['token'], maxlen=max_length, padding=padding_type, truncating=trunc_type)
print(training_sentences)

[[ 598 4081  508 ...    0    0    0]
 [ 130    3  174 ...    0    0    0]
 [ 121 1605 1480 ...    0    0    0]
 ...
 [ 686  573  440 ...    0    0    0]
 [  23 1059 2117 ...    0    0    0]
 [   2  158   98 ...    0    0    0]]


In [27]:
training_label = np.array(train["target"])
print(training_label)

[1 1 1 ... 1 1 1]


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.SimpleRNN(units= 24),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
num_epochs = 30
model.fit(training_sentences, training_label, epochs=num_epochs,validation_split=0.2, verbose=2)

In [ ]:
test_pred = model.predict(test_sentences)
print(test_pred[0])

In [30]:
from keras.models import Sequential
from keras.layers import Input, LSTM, Dense
from keras.layers.embeddings import Embedding
import keras.backend as K

In [31]:
model =tf.keras. Sequential()
model.add(Embedding(vocab_size, 32, input_length=max_length))
# While passing output to next LSTM layer set return_sequence to Ture.
model.add(LSTM(32, return_sequences=True)) 
model.add(LSTM(32))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss=['binary_crossentropy'] , optimizer='adam', metrics=['accuracy'])

In [ ]:
num_epochs = 12
model.fit(training_sentences, training_label, epochs=num_epochs,validation_split=0.2, verbose=2)

Epoch 1/12


## 1. Ridge Classifier (-> NO)

In [ ]:
count_vectorizer = feature_extraction.text.CountVectorizer()
## let's get counts for the first 5 tweets in the data
train_vectors = count_vectorizer.fit_transform(train['txt'])

In [ ]:
test_vectors = count_vectorizer.transform(test["txt"])

In [ ]:
## Our vectors are really big, so we want to push our model's weights
## toward 0 without completely discounting different words - ridge regression 
## is a good way to do this.
clf = linear_model.RidgeClassifier()

In [ ]:
scores = model_selection.cross_val_score(clf, train_vectors, train["target"], cv=3, scoring="f1")
scores

In [ ]:
clf.fit(train_vectors, train["target"])

In [ ]:
test["pred"] = clf.predict(test_vectors)

In [ ]:
display(test[["txt","pred"]])
test.style.set_properties(subset=['text'], **{'width': '3000px'})

## 2. Latent Semantic Analysis

In [ ]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
import scipy.cluster.hierarchy as shc

import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image

%matplotlib inline
sns.set_style("darkgrid")

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import nltk
from sklearn.linear_model import LogisticRegression
from nltk.probability import FreqDist
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.model_selection import train_test_split, GridSearchCV
from matplotlib import cm
import numpy as np
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve
from sklearn.metrics import f1_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import silhouette_score
from sklearn.decomposition import TruncatedSVD, randomized_svd
import string

import warnings
warnings.filterwarnings('ignore')

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
import re
tokenizer = RegexpTokenizer(r'\b\w{3,}\b')

In [ ]:
sample_tfidf = TfidfVectorizer(lowercase=True, 
                      #  stop_words=stop_words, 
                        tokenizer=tokenizer.tokenize,
#                         max_df = 0.8,
                        min_df = 0.1
                       )

In [ ]:
sample_tfidf

In [ ]:
sample_sparse = sample_tfidf.fit_transform(train[:20])

In [ ]:
sample_exp = pd.DataFrame(sample_sparse.toarray(), 
                        columns=sample_tfidf.get_feature_names())

sample_exp.head()

In [ ]:
### 3 RNN